# Generated by Django 4.1.7 on 2023-03-06 02:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Armor",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.URLField()),
                ("stat_modified", models.CharField(default="Defense", max_length=10)),
                ("modifier", models.IntegerField()),
                ("buy_price", models.IntegerField()),
                ("sell_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=600)),
                ("image", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="ArmorLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "armor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.armor"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.location"
                    ),
                ),
            ],
        ),
    ]
