# Generated by Django 4.1.7 on 2023-03-06 04:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Weapon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.URLField()),
                ("stat_modified", models.CharField(default="Offense", max_length=10)),
                ("modifier", models.IntegerField()),
                ("buy_price", models.IntegerField()),
                ("sell_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="WeaponLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.location"
                    ),
                ),
                (
                    "weapon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.weapon"
                    ),
                ),
            ],
        ),
    ]
