# Generated by Django 4.1.7 on 2023-03-06 05:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0002_weapon_weaponlocation"),
    ]

    operations = [
        migrations.CreateModel(
            name="Enemy",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("hit_points", models.PositiveIntegerField()),
                ("attack_power", models.PositiveIntegerField()),
                ("attack_speed", models.PositiveIntegerField()),
                ("defense", models.IntegerField()),
                ("experience", models.IntegerField()),
                ("gold", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("effect", models.CharField(max_length=100)),
                ("buy_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Shield",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("image", models.URLField()),
                ("stat_modified", models.CharField(default="Defense", max_length=10)),
                ("modifier", models.IntegerField()),
                ("buy_price", models.IntegerField()),
                ("sell_price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Spell",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("level_learned", models.IntegerField()),
                ("mp_cost", models.IntegerField()),
                ("spell_type", models.CharField(max_length=10)),
                ("effect", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="ShieldLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.location"
                    ),
                ),
                (
                    "shield",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.shield"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ItemLocation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.item"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.location"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnemySpell",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "enemy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.enemy"
                    ),
                ),
                (
                    "spell",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.spell"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EnemyArea",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                (
                    "enemy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.enemy"
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="data.location"
                    ),
                ),
            ],
        ),
    ]
