# Generated by Django 4.1.7 on 2023-03-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0003_enemy_item_shield_spell_shieldlocation_itemlocation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enemyarea",
            name="enemy",
        ),
        migrations.RemoveField(
            model_name="enemyarea",
            name="location",
        ),
        migrations.RemoveField(
            model_name="enemyspell",
            name="enemy",
        ),
        migrations.RemoveField(
            model_name="enemyspell",
            name="spell",
        ),
        migrations.RemoveField(
            model_name="itemlocation",
            name="item",
        ),
        migrations.RemoveField(
            model_name="itemlocation",
            name="location",
        ),
        migrations.RemoveField(
            model_name="shieldlocation",
            name="location",
        ),
        migrations.RemoveField(
            model_name="shieldlocation",
            name="shield",
        ),
        migrations.RemoveField(
            model_name="weaponlocation",
            name="location",
        ),
        migrations.RemoveField(
            model_name="weaponlocation",
            name="weapon",
        ),
        migrations.AddField(
            model_name="armor",
            name="locations",
            field=models.CharField(default="Tantegel", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enemy",
            name="areas",
            field=models.CharField(default="Tantegel", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="enemy",
            name="spells",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="item",
            name="locations",
            field=models.CharField(default="Tantegel", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shield",
            name="locations",
            field=models.CharField(default="Tantegel", max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weapon",
            name="locations",
            field=models.CharField(default="Tantegel", max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="ArmorLocation",
        ),
        migrations.DeleteModel(
            name="EnemyArea",
        ),
        migrations.DeleteModel(
            name="EnemySpell",
        ),
        migrations.DeleteModel(
            name="ItemLocation",
        ),
        migrations.DeleteModel(
            name="ShieldLocation",
        ),
        migrations.DeleteModel(
            name="WeaponLocation",
        ),
    ]
