# Generated by Django 4.1.7 on 2023-03-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0004_remove_enemyarea_enemy_remove_enemyarea_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enemy",
            name="image",
            field=models.URLField(
                default="https://dragon-quest.org/images/7/74/Slime_DQ_NES.gif"
            ),
            preserve_default=False,
        ),
    ]
