# Generated by Django 4.1.7 on 2023-03-06 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("data", "0005_enemy_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enemy",
            name="attack_power",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="enemy",
            name="attack_speed",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="enemy",
            name="hit_points",
            field=models.IntegerField(),
        ),
    ]
